In [21]:
import numpy as np
import pandas as pd
df=pd.read_csv("studentsmarks1.csv")
df

      student_id  quiz_1_score  quiz_2_score  quiz_3_score  final_exam_score
0              1            65            42            95                10
1              2            77            33            71                87
2              3            38            41            82                65
3              4            97            50            87                48
4              5            79            59            92                48
...          ...           ...           ...           ...               ...
1010        1011            56            22            66                31
1011        1012            70            98            12                93
1012        1013            49            97            32                94
1013        1014            56            78            60                12
1014        1015            91            59            72                53

[1015 rows x 5 columns]

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1015 entries, 0 to 1014
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        1015 non-null   int64
 1   quiz_1_score      1015 non-null   int64
 2   quiz_2_score      1015 non-null   int64
 3   quiz_3_score      1015 non-null   int64
 4   final_exam_score  1015 non-null   int64
dtypes: int64(5)
memory usage: 39.8 KB

In [23]:
df.isna().sum()

student_id          0
quiz_1_score        0
quiz_2_score        0
quiz_3_score        0
final_exam_score    0
dtype: int64

In [98]:
quiz_avg=[]
for i in range(1,df.shape[1]-1):
    print("Avg score of quiz ",i," ",np.average(df.iloc[:,i].values))
    quiz_avg.append(np.average(df.iloc[:,i].values))

Avg score of quiz  1   54.98325123152709
Avg score of quiz  2   55.278817733990145
Avg score of quiz  3   53.62463054187192

In [119]:
avg_score=[]
for i in range(df.shape[0]):
    print("Avg score of student ",i,"\t",np.average(df.iloc[i,1:].values))
    avg_score.append(float(np.average(df.iloc[i,1:].values)))

Avg score of student  0 	 53.0
Avg score of student  1 	 67.0
Avg score of student  2 	 56.5
Avg score of student  3 	 70.5
Avg score of student  4 	 69.5
Avg score of student  5 	 74.5
Avg score of student  6 	 59.25
Avg score of student  7 	 61.0
Avg score of student  8 	 53.25
Avg score of student  9 	 82.75
Avg score of student  10 	 47.5
Avg score of student  11 	 70.5
Avg score of student  12 	 64.5
Avg score of student  13 	 79.75
Avg score of student  14 	 48.25
Avg score of student  15 	 74.0
Avg score of student  16 	 65.75
Avg score of student  17 	 63.0
Avg score of student  18 	 53.75
Avg score of student  19 	 58.0
Avg score of student  20 	 37.25
Avg score of student  21 	 39.75
Avg score of student  22 	 37.75
Avg score of student  23 	 68.75
Avg score of student  24 	 56.75
Avg score of student  25 	 46.25
Avg score of student  26 	 58.5
Avg score of student  27 	 34.0
Avg score of student  28 	 70.75
Avg score of student  29 	 60.5
Avg score of student  30 	 63.5
Avg score of student  31 	 63.0
Avg score of student  32 	 41.25
Avg score of student  33 	 50.0
Avg score of student  34 	 67.25
Avg score of student  35 	 40.25
Avg score of student  36 	 56.5
Avg score of student  37 	 29.25
Avg score of student  38 	 48.5
Avg score of student  39 	 42.0
Avg score of student  40 	 45.75
Avg score of student  41 	 48.25
Avg score of student  42 	 56.25
Avg score of student  43 	 46.25
Avg score of student  44 	 47.0
Avg score of student  45 	 59.0
Avg score of student  46 	 67.5
Avg score of student  47 	 39.5
Avg score of student  48 	 63.25
Avg score of student  49 	 51.5
Avg score of student  50 	 51.0
Avg score of student  51 	 68.5
Avg score of student  52 	 64.5
Avg score of student  53 	 54.25
Avg score of student  54 	 55.0
Avg score of student  55 	 39.5
Avg score of student  56 	 61.75
Avg score of student  57 	 47.5
Avg score of student  58 	 40.5
Avg score of student  59 	 41.25
Avg score of student  60 	 54.5
Avg score of student  61 	 78.25
Avg score of student  62 	 42.0
Avg score of student  63 	 39.75
Avg score of student  64 	 55.0
Avg score of student  65 	 50.25
Avg score of student  66 	 57.25
Avg score of student  67 	 39.0
Avg score of student  68 	 56.25
Avg score of student  69 	 61.5
Avg score of student  70 	 56.0
Avg score of student  71 	 73.25
Avg score of student  72 	 69.0
Avg score of student  73 	 54.5
Avg score of student  74 	 50.5
Avg score of student  75 	 51.5
Avg score of student  76 	 49.5
Avg score of student  77 	 63.5
Avg score of student  78 	 57.25
Avg score of student  79 	 72.0
Avg score of student  80 	 42.75
Avg score of student  81 	 58.5
Avg score of student  82 	 64.75
Avg score of student  83 	 62.0
Avg score of student  84 	 60.75
Avg score of student  85 	 50.75
Avg score of student  86 	 54.25
Avg score of student  87 	 77.75
Avg score of student  88 	 64.75
Avg score of student  89 	 51.5
Avg score of student  90 	 69.75
Avg score of student  91 	 53.25
Avg score of student  92 	 65.5
Avg score of student  93 	 60.25
Avg score of student  94 	 37.75
Avg score of student  95 	 42.25
Avg score of student  96 	 42.0
Avg score of student  97 	 84.75
Avg score of student  98 	 77.0
Avg score of student  99 	 58.0
Avg score of student  100 	 67.25
Avg score of student  101 	 50.5
Avg score of student  102 	 56.75
Avg score of student  103 	 46.75
Avg score of student  104 	 46.5
Avg score of student  105 	 55.75
Avg score of student  106 	 67.5
Avg score of student  107 	 52.75
Avg score of student  108 	 38.0
Avg score of student  109 	 45.0
Avg score of student  110 	 78.25
Avg score of student  111 	 50.5
Avg score of student  112 	 62.0
Avg score of student  113 	 51.0
Avg score of student  114 	 36.75
Avg score of student  115 	 59.75
Avg score of student  116 	 62.75
Avg score of student  117 	 58.75
Avg score of student  118 	 71.75
Avg score of student  119 	 36.5
Avg score of student  120 	 43.25
Avg score of student  121 	 48.75
Avg score of student  122 	 64.25
Avg score of student  123 	 55.5
Avg score of student  124 	 45.75
Avg score of student  125 	 41.25
Avg score of student  126 	 24.5
Avg score of student  127 	 74.75
Avg score of student  128 	 48.75
Avg score of student  129 	 52.5
Avg score of student  130 	 42.5
Avg score of student  131 	 58.5
Avg score of student  132 	 53.25
Avg score of student  133 	 37.5
Avg score of student  134 	 31.75
Avg score of student  135 	 52.75
Avg score of student  136 	 55.75
Avg score of student  137 	 41.75
Avg score of student  138 	 46.0
Avg score of student  139 	 39.0
Avg score of student  140 	 56.75
Avg score of student  141 	 41.5
Avg score of student  142 	 61.75
Avg score of student  143 	 59.75
Avg score of student  144 	 65.25
Avg score of student  145 	 59.0
Avg score of student  146 	 39.0
Avg score of student  147 	 18.0
Avg score of student  148 	 70.5
Avg score of student  149 	 53.0
Avg score of student  150 	 66.5
Avg score of student  151 	 59.75
Avg score of student  152 	 64.25
Avg score of student  153 	 46.25
Avg score of student  154 	 84.25
Avg score of student  155 	 32.5
Avg score of student  156 	 84.75
Avg score of student  157 	 77.25
Avg score of student  158 	 62.5
Avg score of student  159 	 40.25
Avg score of student  160 	 54.75
Avg score of student  161 	 49.5
Avg score of student  162 	 41.5
Avg score of student  163 	 26.0
Avg score of student  164 	 30.5
Avg score of student  165 	 56.75
Avg score of student  166 	 66.0
Avg score of student  167 	 49.0
Avg score of student  168 	 54.5
Avg score of student  169 	 66.25
Avg score of student  170 	 73.5
Avg score of student  171 	 61.0
Avg score of student  172 	 45.75
Avg score of student  173 	 49.75
Avg score of student  174 	 63.25
Avg score of student  175 	 42.5
Avg score of student  176 	 38.0
Avg score of student  177 	 54.25
Avg score of student  178 	 38.25
Avg score of student  179 	 38.0
Avg score of student  180 	 34.0
Avg score of student  181 	 60.25
Avg score of student  182 	 69.0
Avg score of student  183 	 66.5
Avg score of student  184 	 62.0
Avg score of student  185 	 71.5
Avg score of student  186 	 72.5
Avg score of student  187 	 58.0
Avg score of student  188 	 73.5
Avg score of student  189 	 42.0
Avg score of student  190 	 66.75
Avg score of student  191 	 41.25
Avg score of student  192 	 68.5
Avg score of student  193 	 51.0
Avg score of student  194 	 65.25
Avg score of student  195 	 37.75
Avg score of student  196 	 50.0
Avg score of student  197 	 43.5
Avg score of student  198 	 42.75
Avg score of student  199 	 25.5
Avg score of student  200 	 33.75
Avg score of student  201 	 32.5
Avg score of student  202 	 32.5
Avg score of student  203 	 37.25
Avg score of student  204 	 53.75
Avg score of student  205 	 29.5
Avg score of student  206 	 49.0
Avg score of student  207 	 46.75
Avg score of student  208 	 50.5
Avg score of student  209 	 42.5
Avg score of student  210 	 48.25
Avg score of student  211 	 39.75
Avg score of student  212 	 59.25
Avg score of student  213 	 80.5
Avg score of student  214 	 53.0
Avg score of student  215 	 50.5
Avg score of student  216 	 61.75
Avg score of student  217 	 50.5
Avg score of student  218 	 60.5
Avg score of student  219 	 72.75
Avg score of student  220 	 48.75
Avg score of student  221 	 36.0
Avg score of student  222 	 66.5
Avg score of student  223 	 73.75
Avg score of student  224 	 59.25
Avg score of student  225 	 60.0
Avg score of student  226 	 48.0
Avg score of student  227 	 60.25
Avg score of student  228 	 65.75
Avg score of student  229 	 53.75
Avg score of student  230 	 61.25
Avg score of student  231 	 60.5
Avg score of student  232 	 55.25
Avg score of student  233 	 48.0
Avg score of student  234 	 78.25
Avg score of student  235 	 41.5
Avg score of student  236 	 40.0
Avg score of student  237 	 57.75
Avg score of student  238 	 64.5
Avg score of student  239 	 48.0
Avg score of student  240 	 73.75
Avg score of student  241 	 58.25
Avg score of student  242 	 59.75
Avg score of student  243 	 57.5
Avg score of student  244 	 49.25
Avg score of student  245 	 61.0
Avg score of student  246 	 62.0
Avg score of student  247 	 76.5
Avg score of student  248 	 68.25
Avg score of student  249 	 44.25
Avg score of student  250 	 47.25
Avg score of student  251 	 75.75
Avg score of student  252 	 44.75
Avg score of student  253 	 67.5
Avg score of student  254 	 66.25
Avg score of student  255 	 71.5
Avg score of student  256 	 46.5
Avg score of student  257 	 58.25
Avg score of student  258 	 44.25
Avg score of student  259 	 53.5
Avg score of student  260 	 41.75
Avg score of student  261 	 53.25
Avg score of student  262 	 39.0
Avg score of student  263 	 63.75
Avg score of student  264 	 54.5
Avg score of student  265 	 49.75
Avg score of student  266 	 65.75
Avg score of student  267 	 67.5
Avg score of student  268 	 40.75
Avg score of student  269 	 48.25
Avg score of student  270 	 32.75
Avg score of student  271 	 71.5
Avg score of student  272 	 53.25
Avg score of student  273 	 46.5
Avg score of student  274 	 62.75
Avg score of student  275 	 70.5
Avg score of student  276 	 42.75
Avg score of student  277 	 70.75
Avg score of student  278 	 57.0
Avg score of student  279 	 40.75
Avg score of student  280 	 37.0
Avg score of student  281 	 45.25
Avg score of student  282 	 70.25
Avg score of student  283 	 54.75
Avg score of student  284 	 62.5
Avg score of student  285 	 43.25
Avg score of student  286 	 28.0
Avg score of student  287 	 71.0
Avg score of student  288 	 45.5
Avg score of student  289 	 52.25
Avg score of student  290 	 60.5
Avg score of student  291 	 62.5
Avg score of student  292 	 57.75
Avg score of student  293 	 56.5
Avg score of student  294 	 63.25
Avg score of student  295 	 48.25
Avg score of student  296 	 69.0
Avg score of student  297 	 73.75
Avg score of student  298 	 27.25
Avg score of student  299 	 40.75
Avg score of student  300 	 61.75
Avg score of student  301 	 53.0
Avg score of student  302 	 72.75
Avg score of student  303 	 64.0
Avg score of student  304 	 71.25
Avg score of student  305 	 57.5
Avg score of student  306 	 62.75
Avg score of student  307 	 67.75
Avg score of student  308 	 41.5
Avg score of student  309 	 62.0
Avg score of student  310 	 45.75
Avg score of student  311 	 38.5
Avg score of student  312 	 31.75
Avg score of student  313 	 57.25
Avg score of student  314 	 57.25
Avg score of student  315 	 50.75
Avg score of student  316 	 55.0
Avg score of student  317 	 59.75
Avg score of student  318 	 75.0
Avg score of student  319 	 53.25
Avg score of student  320 	 51.25
Avg score of student  321 	 47.25
Avg score of student  322 	 69.5
Avg score of student  323 	 46.5
Avg score of student  324 	 59.75
Avg score of student  325 	 68.75
Avg score of student  326 	 57.75
Avg score of student  327 	 60.5
Avg score of student  328 	 34.75
Avg score of student  329 	 59.75
Avg score of student  330 	 58.5
Avg score of student  331 	 47.25
Avg score of student  332 	 60.5
Avg score of student  333 	 64.5
Avg score of student  334 	 46.25
Avg score of student  335 	 67.25
Avg score of student  336 	 88.0
Avg score of student  337 	 66.75
Avg score of student  338 	 30.25
Avg score of student  339 	 57.75
Avg score of student  340 	 62.5
Avg score of student  341 	 44.5
Avg score of student  342 	 40.25
Avg score of student  343 	 61.5
Avg score of student  344 	 64.75
Avg score of student  345 	 39.0
Avg score of student  346 	 45.75
Avg score of student  347 	 49.5
Avg score of student  348 	 54.25
Avg score of student  349 	 55.75
Avg score of student  350 	 59.0
Avg score of student  351 	 38.0
Avg score of student  352 	 62.25
Avg score of student  353 	 26.75
Avg score of student  354 	 31.25
Avg score of student  355 	 38.75
Avg score of student  356 	 56.25
Avg score of student  357 	 42.25
Avg score of student  358 	 28.25
Avg score of student  359 	 63.0
Avg score of student  360 	 67.0
Avg score of student  361 	 56.75
Avg score of student  362 	 51.75
Avg score of student  363 	 36.0
Avg score of student  364 	 48.25
Avg score of student  365 	 48.0
Avg score of student  366 	 60.25
Avg score of student  367 	 58.75
Avg score of student  368 	 65.25
Avg score of student  369 	 36.0
Avg score of student  370 	 42.5
Avg score of student  371 	 52.0
Avg score of student  372 	 47.5
Avg score of student  373 	 66.0
Avg score of student  374 	 62.75
Avg score of student  375 	 52.0
Avg score of student  376 	 32.0
Avg score of student  377 	 63.75
Avg score of student  378 	 63.0
Avg score of student  379 	 59.0
Avg score of student  380 	 53.25
Avg score of student  381 	 62.75
Avg score of student  382 	 58.0
Avg score of student  383 	 55.75
Avg score of student  384 	 51.75
Avg score of student  385 	 58.0
Avg score of student  386 	 35.25
Avg score of student  387 	 70.75
Avg score of student  388 	 34.75
Avg score of student  389 	 57.75
Avg score of student  390 	 35.5
Avg score of student  391 	 77.25
Avg score of student  392 	 63.5
Avg score of student  393 	 36.0
Avg score of student  394 	 39.25
Avg score of student  395 	 49.0
Avg score of student  396 	 46.25
Avg score of student  397 	 52.75
Avg score of student  398 	 52.5
Avg score of student  399 	 79.25
Avg score of student  400 	 41.25
Avg score of student  401 	 52.0
Avg score of student  402 	 50.0
Avg score of student  403 	 77.5
Avg score of student  404 	 43.25
Avg score of student  405 	 41.75
Avg score of student  406 	 67.75
Avg score of student  407 	 73.0
Avg score of student  408 	 72.25
Avg score of student  409 	 49.5
Avg score of student  410 	 56.5
Avg score of student  411 	 46.75
Avg score of student  412 	 74.5
Avg score of student  413 	 28.75
Avg score of student  414 	 45.25
Avg score of student  415 	 49.5
Avg score of student  416 	 48.0
Avg score of student  417 	 62.25
Avg score of student  418 	 50.5
Avg score of student  419 	 33.5
Avg score of student  420 	 59.75
Avg score of student  421 	 63.25
Avg score of student  422 	 67.25
Avg score of student  423 	 48.75
Avg score of student  424 	 63.75
Avg score of student  425 	 75.75
Avg score of student  426 	 54.5
Avg score of student  427 	 72.75
Avg score of student  428 	 29.75
Avg score of student  429 	 45.0
Avg score of student  430 	 66.75
Avg score of student  431 	 70.0
Avg score of student  432 	 41.75
Avg score of student  433 	 66.0
Avg score of student  434 	 52.25
Avg score of student  435 	 53.5
Avg score of student  436 	 79.75
Avg score of student  437 	 65.25
Avg score of student  438 	 56.25
Avg score of student  439 	 55.75
Avg score of student  440 	 72.5
Avg score of student  441 	 72.75
Avg score of student  442 	 66.5
Avg score of student  443 	 47.5
Avg score of student  444 	 57.0
Avg score of student  445 	 51.25
Avg score of student  446 	 84.0
Avg score of student  447 	 47.25
Avg score of student  448 	 59.25
Avg score of student  449 	 60.0
Avg score of student  450 	 36.0
Avg score of student  451 	 53.0
Avg score of student  452 	 47.5
Avg score of student  453 	 37.0
Avg score of student  454 	 55.25
Avg score of student  455 	 53.0
Avg score of student  456 	 55.5
Avg score of student  457 	 43.0
Avg score of student  458 	 53.75
Avg score of student  459 	 38.75
Avg score of student  460 	 51.0
Avg score of student  461 	 93.25
Avg score of student  462 	 55.75
Avg score of student  463 	 42.75
Avg score of student  464 	 38.0
Avg score of student  465 	 71.75
Avg score of student  466 	 53.25
Avg score of student  467 	 55.75
Avg score of student  468 	 54.25
Avg score of student  469 	 78.0
Avg score of student  470 	 67.75
Avg score of student  471 	 14.75
Avg score of student  472 	 68.5
Avg score of student  473 	 63.5
Avg score of student  474 	 62.5
Avg score of student  475 	 45.25
Avg score of student  476 	 50.25
Avg score of student  477 	 40.0
Avg score of student  478 	 45.25
Avg score of student  479 	 57.5
Avg score of student  480 	 52.25
Avg score of student  481 	 32.0
Avg score of student  482 	 38.5
Avg score of student  483 	 48.0
Avg score of student  484 	 33.75
Avg score of student  485 	 54.25
Avg score of student  486 	 34.0
Avg score of student  487 	 66.0
Avg score of student  488 	 55.0
Avg score of student  489 	 50.0
Avg score of student  490 	 55.0
Avg score of student  491 	 62.5
Avg score of student  492 	 51.75
Avg score of student  493 	 42.5
Avg score of student  494 	 71.25
Avg score of student  495 	 60.5
Avg score of student  496 	 35.0
Avg score of student  497 	 60.25
Avg score of student  498 	 59.25
Avg score of student  499 	 69.5
Avg score of student  500 	 69.5
Avg score of student  501 	 86.5
Avg score of student  502 	 55.75
Avg score of student  503 	 32.75
Avg score of student  504 	 46.25
Avg score of student  505 	 68.75
Avg score of student  506 	 57.0
Avg score of student  507 	 63.25
Avg score of student  508 	 60.25
Avg score of student  509 	 49.5
Avg score of student  510 	 58.0
Avg score of student  511 	 75.25
Avg score of student  512 	 46.75
Avg score of student  513 	 61.0
Avg score of student  514 	 41.75
Avg score of student  515 	 62.5
Avg score of student  516 	 43.0
Avg score of student  517 	 55.75
Avg score of student  518 	 92.25
Avg score of student  519 	 69.0
Avg score of student  520 	 73.5
Avg score of student  521 	 50.25
Avg score of student  522 	 60.5
Avg score of student  523 	 33.0
Avg score of student  524 	 37.0
Avg score of student  525 	 51.75
Avg score of student  526 	 43.0
Avg score of student  527 	 46.75
Avg score of student  528 	 45.75
Avg score of student  529 	 55.75
Avg score of student  530 	 61.25
Avg score of student  531 	 31.5
Avg score of student  532 	 69.0
Avg score of student  533 	 59.75
Avg score of student  534 	 72.0
Avg score of student  535 	 62.0
Avg score of student  536 	 51.0
Avg score of student  537 	 49.5
Avg score of student  538 	 61.5
Avg score of student  539 	 60.75
Avg score of student  540 	 48.25
Avg score of student  541 	 46.0
Avg score of student  542 	 48.75
Avg score of student  543 	 68.75
Avg score of student  544 	 73.25
Avg score of student  545 	 45.5
Avg score of student  546 	 59.75
Avg score of student  547 	 71.0
Avg score of student  548 	 53.25
Avg score of student  549 	 40.75
Avg score of student  550 	 90.0
Avg score of student  551 	 59.5
Avg score of student  552 	 48.75
Avg score of student  553 	 45.25
Avg score of student  554 	 15.25
Avg score of student  555 	 45.25
Avg score of student  556 	 48.25
Avg score of student  557 	 52.25
Avg score of student  558 	 42.5
Avg score of student  559 	 38.25
Avg score of student  560 	 46.75
Avg score of student  561 	 49.25
Avg score of student  562 	 48.25
Avg score of student  563 	 53.5
Avg score of student  564 	 69.5
Avg score of student  565 	 54.5
Avg score of student  566 	 51.5
Avg score of student  567 	 35.25
Avg score of student  568 	 30.75
Avg score of student  569 	 61.25
Avg score of student  570 	 66.25
Avg score of student  571 	 52.0
Avg score of student  572 	 35.5
Avg score of student  573 	 65.25
Avg score of student  574 	 52.25
Avg score of student  575 	 44.5
Avg score of student  576 	 58.0
Avg score of student  577 	 60.5
Avg score of student  578 	 41.75
Avg score of student  579 	 91.0
Avg score of student  580 	 60.25
Avg score of student  581 	 50.5
Avg score of student  582 	 30.0
Avg score of student  583 	 24.75
Avg score of student  584 	 56.75
Avg score of student  585 	 81.25
Avg score of student  586 	 56.25
Avg score of student  587 	 52.25
Avg score of student  588 	 46.75
Avg score of student  589 	 47.0
Avg score of student  590 	 59.25
Avg score of student  591 	 74.5
Avg score of student  592 	 63.25
Avg score of student  593 	 47.5
Avg score of student  594 	 50.0
Avg score of student  595 	 71.0
Avg score of student  596 	 47.5
Avg score of student  597 	 59.25
Avg score of student  598 	 53.75

In [120]:
print("The quiz with the highest average marks is : Quiz -",quiz_avg.index(max(quiz_avg))+1,"with the average score of : ",max(quiz_avg))

The quiz with the highest average marks is : Quiz - 2 with the average score of :  55.278817733990145

In [121]:
sorted_list = sorted(enumerate(avg_score,1), key=lambda x: x[1], reverse=True)
top_20 = sorted_list[:20]
print(top_20)

[(462, 93.25), (519, 92.25), (788, 91.5), (580, 91.0), (551, 90.0), (838, 89.0), (337, 88.0), (892, 87.75), (737, 87.25), (502, 86.5), (720, 85.0), (98, 84.75), (157, 84.75), (155, 84.25), (447, 84.0), (850, 83.0), (10, 82.75), (896, 82.75), (990, 82.25), (960, 81.75)]

In [124]:
count=0
for i in avg_score:
    if i>=60:
        count+=1
print("The number of students who passed are :",count)

The number of students who passed are : 369

In [126]:
lr=pd.read_csv("salary_data.csv")
lr

    YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [146]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
X=np.array(lr.iloc[:,0]).reshape(-1, 1)
y=np.array(lr.iloc[:,1])
model=LinearRegression()
model.fit(X,y)
x=np.array([5]).reshape(-1, 1)
y=model.predict(x)
print("The predicted salary should be : Rs %0.2f"%y[0])

The predicted salary should be : Rs 73042.01

In [152]:
sent=input("Enter the sentence : ")
lst=sent.split(" ")
sw=pd.Series(lst)
pw=sw.value_counts()
print(pw['was'])

Enter the sentence : Nory was a Catholic because her mother was a Catholic, and Noryâ€™s mother was a Catholic because her father was a Catholic, and her father was a Catholic because his mother was a Catholic, or had been
6